export const navLinks = [
	{ title: "work", url: "/" },
	{ title: "about", url: "/about" },
	{ title: "contact", url: "/contact" },
];

export const imageCollection = [
	{
		id: "project01",
		imageCollection: [
			"/assets/img1-1.png",
			"/assets/img1-2.png",
			"/assets/img1-3.png",
			"/assets/img1-4.png",
			"/assets/img1-5.png",
			"/assets/img1-6.png",
			"/assets/img1-7.png",
		],
	},
	{
		id: "project02",
		imageCollection: [
			"/assets/img2-1.png",
			"/assets/img2-2.png",
			"/assets/img2-3.png",
			"/assets/img2-4.png",
			"/assets/img2-5.png",
			"/assets/img2-6.png",
			"/assets/img2-7.png",
		],
	},
	{
		id: "project03",
		imageCollection: [
			"/assets/img3-1.png",
			"/assets/img3-2.png",
			"/assets/img3-3.png",
			"/assets/img3-4.png",
			"/assets/img3-5.png",
			"/assets/img3-6.png",
			"/assets/img3-7.png",
		],
	},
	{
		id: "project04",
		imageCollection: [
			"/assets/img4-1.png",
			"/assets/img4-2.png",
			"/assets/img4-3.png",
			"/assets/img4-4.png",
			"/assets/img4-5.png",
			"/assets/img4-6.png",
			"/assets/img4-7.png",
		],
	},
	{
		id: "project05",
		imageCollection: [
			"/assets/img5-1.png",
			"/assets/img5-2.png",
			"/assets/img5-3.png",
			"/assets/img5-4.png",
			"/assets/img5-5.png",
			"/assets/img5-6.png",
			"/assets/img5-7.png",
		],
	},
	{
		id: "project06",
		imageCollection: [
			"/assets/img6-1.png",
			"/assets/img6-2.png",
			"/assets/img6-3.png",
			"/assets/img6-4.png",
			"/assets/img6-5.png",
			"/assets/img6-6.png",
			"/assets/img6-7.png",
		],
	},
	{
		id: "project07",
		imageCollection: [
			"/assets/img7-1.png",
			"/assets/img7-2.png",
			"/assets/img7-3.png",
			"/assets/img7-4.png",
			"/assets/img7-5.png",
			"/assets/img7-6.png",
			"/assets/img7-7.png",
		],
	},
	{
		id: "project08",
		imageCollection: [
			"/assets/img8-1.png",
			"/assets/img8-2.png",
			"/assets/img8-3.png",
			"/assets/img8-4.png",
			"/assets/img8-5.png",
			"/assets/img8-6.png",
			"/assets/img8-7.png",
		],
	},
	{
		id: "project09",
		imageCollection: [
			"/assets/img9-1.png",
			"/assets/img9-2.png",
			"/assets/img9-3.png",
			"/assets/img9-4.png",
			"/assets/img9-5.png",
			"/assets/img9-6.png",
			"/assets/img9-7.png",
		],
	},
	{
		id: "project10",
		imageCollection: [
			"/assets/img10-1.png",
			"/assets/img10-2.png",
			"/assets/img10-3.png",
			"/assets/img10-4.png",
			"/assets/img10-5.png",
			"/assets/img10-6.png",
			"/assets/img10-7.png",
		],
	},
	{
		id: "project11",
		imageCollection: [
			"/assets/img11-1.png",
			"/assets/img11-2.png",
			"/assets/img11-3.png",
			"/assets/img11-4.png",
			"/assets/img11-5.png",
			"/assets/img11-6.png",
			"/assets/img11-7.png",
		],
	},
	{
		id: "project12",
		imageCollection: [
			"/assets/img12-1.png",
			"/assets/img12-2.png",
			"/assets/img12-3.png",
			"/assets/img12-4.png",
			"/assets/img12-5.png",
			"/assets/img12-6.png",
			"/assets/img12-7.png",
		],
	},
];

export const landingImages = [
	{
		id: "1",
		projectName: "Project Shoot 1",
		imageUrl: "/assets/img1.png",
		imageCollection: [
			"/assets/img1-1.png",
			"/assets/img1-2.png",
			"/assets/img1-3.png",
			"/assets/img1-4.png",
			"/assets/img1-5.png",
			"/assets/img1-6.png",
			"/assets/img1-7.png",
		],
		alt: "test",
		shootType: "Baby Shower Photoshoot",
		location: "Nagpur",
		camera: "Canon EOS 60D",
		year: "2023",
	},
	{
		id: "2",
		projectName: "Project Shoot 2",
		imageUrl: "/assets/img2.png",
		imageCollection: [
			"/assets/img2-1.png",
			"/assets/img2-2.png",
			"/assets/img2-3.png",
			"/assets/img2-4.png",
			"/assets/img2-5.png",
			"/assets/img2-6.png",
			"/assets/img2-7.png",
		],
		alt: "test",
		shootType: "Baby Shower Photoshoot",
		location: "Nagpur",
		camera: "Canon EOS 60D",
		year: "2023",
	},
	{
		id: "3",
		projectName: "Project Shoot 3",
		imageUrl: "/assets/img3.png",
		imageCollection: [
			"/assets/img3-1.png",
			"/assets/img3-2.png",
			"/assets/img3-3.png",
			"/assets/img3-4.png",
			"/assets/img3-5.png",
			"/assets/img3-6.png",
			"/assets/img3-7.png",
		],
		alt: "test",
		shootType: "Baby Shower Photoshoot",
		location: "Nagpur",
		camera: "Canon EOS 60D",
		year: "2023",
	},
	{
		id: "4",
		projectName: "Project Shoot 4",
		imageUrl: "/assets/img4.png",
		imageCollection: [
			"/assets/img4-1.png",
			"/assets/img4-2.png",
			"/assets/img4-3.png",
			"/assets/img4-4.png",
			"/assets/img4-5.png",
			"/assets/img4-6.png",
			"/assets/img4-7.png",
		],
		alt: "test",
		shootType: "Portfolio photoshoot",
		location: "Nagpur",
		camera: "Canon EOS 60D",
		year: "2023",
	},
	{
		id: "5",
		projectName: "Project Shoot 5",
		imageUrl: "/assets/img5.png",
		imageCollection: [
			"/assets/img5-1.png",
			"/assets/img5-2.png",
			"/assets/img5-3.png",
			"/assets/img5-4.png",
			"/assets/img5-5.png",
			"/assets/img5-6.png",
			"/assets/img5-7.png",
		],
		alt: "test",
		shootType: "Portfolio photoshoot",
		location: "Nagpur",
		camera: "Canon EOS 60D",
		year: "2023",
	},
	{
		id: "6",
		projectName: "Project Shoot 6",
		imageUrl: "/assets/img6.png",
		imageCollection: [
			"/assets/img6-1.png",
			"/assets/img6-2.png",
			"/assets/img6-3.png",
			"/assets/img6-4.png",
			"/assets/img6-5.png",
			"/assets/img6-6.png",
			"/assets/img6-7.png",
		],
		alt: "test",
		shootType: "Portfolio photoshoot",
		location: "Nagpur",
		camera: "Canon EOS 60D",
		year: "2023",
	},
	{
		id: "7",
		projectName: "Project Shoot 7",
		imageUrl: "/assets/img7.png",
		imageCollection: [
			"/assets/img7-1.png",
			"/assets/img7-2.png",
			"/assets/img7-3.png",
			"/assets/img7-4.png",
			"/assets/img7-5.png",
			"/assets/img7-6.png",
			"/assets/img7-7.png",
		],
		alt: "test",
		shootType: "Maternity Photoshoot",
		location: "Nagpur",
		camera: "Canon EOS 60D",
		year: "2023",
	},
	{
		id: "8",
		projectName: "Project Shoot 8",
		imageUrl: "/assets/img8.png",
		imageCollection: [
			"/assets/img8-1.png",
			"/assets/img8-2.png",
			"/assets/img8-3.png",
			"/assets/img8-4.png",
			"/assets/img8-5.png",
			"/assets/img8-6.png",
			"/assets/img8-7.png",
		],
		alt: "test",
		shootType: "Maternity Photoshoot",
		location: "Nagpur",
		camera: "Canon EOS 60D",
		year: "2023",
	},
	{
		id: "9",
		projectName: "Project Shoot 9",
		imageUrl: "/assets/img9.png",
		imageCollection: [
			"/assets/img9-1.png",
			"/assets/img9-2.png",
			"/assets/img9-3.png",
			"/assets/img9-4.png",
			"/assets/img9-5.png",
			"/assets/img9-6.png",
			"/assets/img9-7.png",
		],
		alt: "test",
		shootType: "Maternity Photoshoot",
		location: "Nagpur",
		camera: "Canon EOS 60D",
		year: "2023",
	},
	{
		id: "10",
		projectName: "Project Shoot 10",
		imageUrl: "/assets/img10.png",
		imageCollection: [
			"/assets/img10-1.png",
			"/assets/img10-2.png",
			"/assets/img10-3.png",
			"/assets/img10-4.png",
			"/assets/img10-5.png",
			"/assets/img10-6.png",
			"/assets/img10-7.png",
		],
		alt: "test",
		shootType: "Maternity Photoshoot",
		location: "Nagpur",
		camera: "Canon EOS 60D",
		year: "2023",
	},
	{
		id: "11",
		projectName: "Project Shoot 11",
		imageUrl: "/assets/img11.png",
		imageCollection: [
			"/assets/img11-1.png",
			"/assets/img11-2.png",
			"/assets/img11-3.png",
			"/assets/img11-4.png",
			"/assets/img11-5.png",
			"/assets/img11-6.png",
			"/assets/img11-7.png",
		],
		alt: "test",
		shootType: "Maternity Photoshoot",
		location: "Nagpur",
		camera: "Canon EOS 60D",
		year: "2023",
	},
	{
		id: "12",
		projectName: "Project Shoot 12",
		imageUrl: "/assets/img12.png",
		imageCollection: [
			"/assets/img12-1.png",
			"/assets/img12-2.png",
			"/assets/img12-3.png",
			"/assets/img12-4.png",
			"/assets/img12-5.png",
			"/assets/img12-6.png",
			"/assets/img12-7.png",
		],
		alt: "test",
		shootType: "Baby Shower Photoshoot",
		location: "Nagpur",
		camera: "Canon EOS 60D",
		year: "2023",
	},
];
